# Generated by Django 6.0.3 on 2026-04-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='user',
        ),
    ]
